# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 04 Feb 2021 11:58:39 +0000
*               @ALL          1
*               @user         8
