<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: thomasblakeney
 * Date: Thu, 04 Feb 2021 13:05:28 +0100
 */

$conf['title'] = 'ArisCorp Starship-Exkurs';
$conf['lang'] = 'de';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'recent,revisions,register,resendpwd,profile_delete,edit,check,rss,subscribe,unsubscribe,source,export_raw';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
