# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 04 Feb 2021 11:58:39 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

thomasblakeney:$2y$10$Bvtmy8ujUauwXuqngIP7uODkNaAuVyQEaO6lEeV3.vE5FXDxvI/l2:Lucas:xxx.xxx@xxx.xxx:admin,user
